version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
branches:
  only:
  - master
  - dev
  - next
  - core
clone_folder: c:\azure-webjobs-sdk-extensions
install:
- ps: >
    $env:CommitHash = "$env:APPVEYOR_REPO_COMMIT"
environment:
  BUILD_NUMBER: '%APPVEYOR_BUILD_NUMBER%'
  IncludeBuildNumberInVersion: 1
build_script:
- ps: |
    dotnet --version

    dotnet build -v q

    $projects = `
        "WebJobs.Extensions", `
        "WebJobs.Extensions.CosmosDB", `
        "WebJobs.Extensions.Http", `
        "WebJobs.Extensions.MobileApps", `
        "WebJobs.Extensions.Twilio", `
        "WebJobs.Extensions.SendGrid"

    if($env:IncludeBuildNumberInVersion -eq "1")
    {
        Write-Host "Generating nuget packages with build number."
        foreach ($project in $projects)
        {
            dotnet pack src\$project\$project.csproj -o ..\..\buildoutput --no-build --version-suffix "-$env:APPVEYOR_BUILD_NUMBER"
        }       
    }
    else
    {
        Write-Host "Generating nuget packages without build number."
        foreach ($project in $projects)
        {
            dotnet pack src\$project\$project.csproj -o ..\..\buildoutput --no-build
        }    
    }
test_script:
- ps: >-
    dotnet test .\test\WebJobs.Extensions.Tests\ -v q --no-build -p:ParallelizeTestCollections=false
artifacts:
- path: buildoutput\*.nupkg
  name: Packages